### ISSUE TITLE
Käyttäjänä voin help-komennolla listata saatavilla olevat käskyt ja niiden lyhyet kuvaukset

### ISSUE THREAD

**Issue by turunenv** [turunenv/ohtu-s23-miniprojekti#12]
- [x] Käyttöliittymä näyttää käyttäjällä vaihtoehdon valita help-komento
- [x] Help-komento esittää käyttäjälle valittavina olevat komennot ja niiden lyhyet kuvaukset

**Comment by nikomakir** [comment]
Hyväksymiskriteerit:

- Aloitusvalikossa on vaihtoehto selkeästi esillä, että help-komennolla saa tulostettua ohjeet
- Ohjeet tulostuvat syöttämällä "help" aloitusvalikossa
