### ISSUE TITLE
Käyttäjä ei pysty antamaan selkeästi virheellisiä syötteitä

### ISSUE THREAD

**Issue by emlyy** [turunenv/ohtu-s23-miniprojekti#14]

**Comment by rpessi** [comment]
Mun tekemä pull-request ratkaisee tän osittain. Rich-kirjastossa on Prompt, jonka avulla pystyy antamaan promptissa käyttäjälle vain sallitut vastausvaihtoehdot, eikä käyttäjältä hyväksytä muista vastauuksia. Laitoin mun pullariin näitä prompteja soveltuviin kohtiin, mutta jotkut kohdat vaatis laajempaa refaktorointia tai tarkempaa tutustumista [Richin prompteihin](https://rich.readthedocs.io/en/stable/prompt.html).
