### ISSUE TITLE
Käyttäjänä voin lisätä article-muotoisen viitteen järjestelmään

### ISSUE THREAD

**Issue by turunenv** [turunenv/ohtu-s23-miniprojekti#6]
- [x] tietokannassa oma talulu articleille
- [x] reference_service luo ArticleReference-olion ja antaa sen reference_repositorylle
- [x] article voidaan hakea ja poistaa ref_keytä käyttäen
- [x] app kysyy oikeat kentät, kun käyttäjä lisää article-tyyppistä viitettä
- [x] ArticleReference-luokka on olemassa
- [x] testit

**Comment by nikomakir** [comment]
Done

**Comment by emlyy** [comment]
Hyväksymistestit:
[add_article_reference_robot.py](https://github.com/turunenv/ohtu-s23-miniprojekti/blob/main/src/tests/robot/add_article_reference.robot)
[delete_reference.robot](https://github.com/turunenv/ohtu-s23-miniprojekti/blob/main/src/tests/robot/delete_reference.robot)
